import React, { createContext, useContext, useEffect, useState } from 'react';

const LanguageContext = createContext();

const languages = {
  en: { name: 'English', code: 'en', font: 'font-sans' },
  ta: { name: 'தமிழ்', code: 'ta', font: 'font-tamil' },
  te: { name: 'తెలుగు', code: 'te', font: 'font-telugu' },
  kn: { name: 'ಕನ್ನಡ', code: 'kn', font: 'font-kannada' }
};

const translations = {
  en: {
    appTitle: 'CampusHealth Workspace',
    adminDashboardTitle: 'Admin Dashboard',
    appSubtitle: 'AI-powered campus mental wellness',
    dashboard: 'Dashboard',
    chatbot: 'AI Chatbot',
    screening: 'Screening',
    screeningFull: 'Mental Health Screening',
    mlPredict: 'ML Predict',
    appointments: 'Appointments',
    counselors: 'Counselors',
    activities: 'Activities',
    activitiesManagement: 'Activities Management',
    activityAnalysis: 'Activity Analysis',
    resources: 'Resources',
    forum: 'Forum',
    profile: 'Profile',
    users: 'Users',
    analytics: 'Analytics',
    reports: 'Reports',
    adminStudio: 'Admin Studio',
    adminPanel: 'Admin Panel',
    campusMentalHealth: 'Campus Mental Health',
    wellnessSaaS: 'Wellness SaaS',
    settings: 'Settings',
    theme: 'Theme',
    light: 'Light',
    dark: 'Dark',
    highContrast: 'High Contrast',
    fontSize: 'Font Size',
    small: 'Small',
    medium: 'Medium',
    large: 'Large',
    savingSettings: 'Saving settings…',
    notifications: 'Notifications',
    unreadNotifications: 'Notifications, {{count}} unread',
    logout: 'Logout',
    language: 'Language',
    welcomeBack: 'Welcome back, {{name}}!',
    department: 'Department',
    semester: 'Semester',
    studentId: 'Student ID',
    notAdded: 'Not added',
    retry: 'Retry',
    dashboardLoadError: 'Some dashboard data could not be loaded. Please refresh to try again.',
    loadingDashboard: 'Loading your dashboard...',
    quickActions: 'Quick Actions',
    bookAppointment: 'Book Appointment',
    bookAppointmentDescription: 'Schedule a session with a counselor',
    startAIChat: 'Start AI Chat',
    startAIChatDescription: 'Talk to our AI chatbot for instant support',
    takeAssessment: 'Take Assessment',
    takeAssessmentDescription: 'Assess your mental health with validated tools',
    wellnessEvents: 'Wellness Events',
    wellnessEventsDescription: 'Join workshops, circles, and campus wellbeing sessions',
    viewCounselors: 'View Counselors',
    viewCounselorsDescription: 'Find the right counselor for your needs',
    mentalHealthSummary: 'Mental Health Summary',
    trackWellbeingBaseline: 'Track your wellbeing baseline',
    trackWellbeingMessage: 'Take a screening to see your latest PHQ-9, GAD-7, and risk summary here.',
    latestPhqScore: 'Latest PHQ-9 Score',
    latestGadScore: 'Latest GAD-7 Score',
    pendingPhq: 'Pending PHQ-9',
    pendingGad: 'Pending GAD-7',
    riskLevel: 'Risk level',
    lastAssessment: 'Last assessment',
    aiChatSummary: 'AI Chat Summary',
    continueChat: 'Continue Chat',
    startGuidedCheckin: 'Start a guided AI check-in',
    startGuidedCheckinMessage: 'Start a confidential AI chat whenever you need a quick check-in.',
    totalConversations: 'Total Conversations',
    savedChatSessions: 'Saved chat sessions',
    lastChat: 'Last Chat',
    recentSession: 'Recent session',
    upcomingWellnessEvents: 'Upcoming Wellness Events',
    browseEvents: 'Browse Events',
    buildWellnessCalendar: 'Build your wellness calendar',
    buildWellnessCalendarMessage: 'Register for a campus wellness event to see it here.',
    exploreEvents: 'Explore Events',
    recommendedEvents: 'Recommended Events',
    viewAll: 'View All',
    noRecommendations: 'No recommendations available',
    noRecommendationsMessage: 'New wellbeing recommendations will appear as events are added.',
    appointmentSummary: 'Appointment Summary',
    planCounselingSession: 'Plan your next counseling session',
    planCounselingSessionMessage: 'Book a session and the date, time, meeting type, and status will appear here.',
    counselor: 'Counselor',
    counselingSession: 'Counseling session',
    date: 'Date',
    time: 'Time',
    meetingType: 'Meeting type',
    online: 'Online',
    inPerson: 'In person',
    meetingId: 'Meeting ID',
    openMeeting: 'Open meeting',
    recentActivity: 'Recent Activity',
    noRecentActivity: 'No recent activity',
    noRecentActivityMessage: 'Appointment updates, assessments, and AI conversations will appear here.',
    todaysMentalHealthTip: "Today's Mental Health Tip",
    practiceGratitude: 'Practice Gratitude',
    gratitudeTip: "Take a moment to write down three things you're grateful for today. This simple practice can help improve your mood and overall well-being.",
    welcomeCounselor: 'Welcome, {{name}}',
    counselorIntro: 'Manage your appointments, view student screenings, and respond to messages.',
    viewAppointments: 'View Appointments',
    viewAppointmentsDescription: 'Review and manage upcoming sessions',
    shareResources: 'Share Resources',
    shareResourcesDescription: 'Recommend helpful materials to students',
    activityAnalysisDescription: 'Create activities and view results',
    community: 'Community',
    communityDescription: 'Engage with peer support threads',
    welcomeAdministrator: 'Welcome, Administrator',
    adminIntro: 'Quick access to system analytics, users and settings.',
    viewPlatformUsage: 'View platform usage',
    manageUsers: 'Manage Users',
    manageUsersDescription: 'Roles, status and permissions',
    curateContent: 'Curate and approve content',
    chatbotIntroDescription: 'Get instant mental health support and guidance',
    chatbotIntroTitle: 'Start a Conversation',
    chatbotIntroBody: 'Our AI chatbot is here to provide 24/7 mental health support. Start chatting to get personalized assistance.',
    startChat: 'Start Chat',
    chatbotAssistantLabel: 'AI Assistant',
    typeMessage: 'Type your message...',
    chatbotGreetingFallback: "Hello! I'm your AI mental health assistant. How are you feeling today? I'm here to listen and provide support.",
    chatbotErrorFallback: "Sorry, I couldn't respond right now. Please try again in a moment.",
    screeningDescription: 'Assess your mental health with validated tools',
    phqDescription: 'Patient Health Questionnaire-9 for depression screening',
    gadDescription: 'Generalized Anxiety Disorder-7 for anxiety screening',
    pssDescription: 'Perceived Stress Scale-10 for stress assessment',
    phqQ1: 'Little interest or pleasure in doing things',
    phqQ2: 'Feeling down, depressed, or hopeless',
    phqQ3: 'Trouble falling or staying asleep, or sleeping too much',
    phqQ4: 'Feeling tired or having little energy',
    phqQ5: 'Poor appetite or overeating',
    phqQ6: 'Feeling bad about yourself - or that you are a failure or have let yourself or your family down',
    phqQ7: 'Trouble concentrating on things, such as reading the newspaper or watching television',
    phqQ8: 'Moving or speaking so slowly that other people could have noticed, or the opposite - being so fidgety or restless that you have been moving around a lot more than usual',
    phqQ9: 'Thoughts that you would be better off dead, or of hurting yourself',
    gadQ1: 'Feeling nervous, anxious, or on edge',
    gadQ2: 'Not being able to stop or control worrying',
    gadQ3: 'Worrying too much about different things',
    gadQ4: 'Trouble relaxing',
    gadQ5: 'Being so restless that it is hard to sit still',
    gadQ6: 'Becoming easily annoyed or irritable',
    gadQ7: 'Feeling afraid, as if something awful might happen',
    pssQ1: 'In the last month, how often have you been upset because of something that happened unexpectedly?',
    pssQ2: 'In the last month, how often have you felt that you were unable to control the important things in your life?',
    pssQ3: 'In the last month, how often have you felt nervous and stressed?',
    pssQ4: 'In the last month, how often have you felt confident about your ability to handle your personal problems?',
    pssQ5: 'In the last month, how often have you felt that things were going your way?',
    pssQ6: 'In the last month, how often have you found that you could not cope with all the things that you had to do?',
    pssQ7: 'In the last month, how often have you been able to control irritations in your life?',
    pssQ8: 'In the last month, how often have you felt that you were on top of things?',
    pssQ9: 'In the last month, how often have you been angered because of things that were outside of your control?',
    pssQ10: 'In the last month, how often have you felt difficulties were piling up so high that you could not overcome them?',
    notAtAll: 'Not at all',
    severalDays: 'Several days',
    moreThanHalfDays: 'More than half the days',
    nearlyEveryDay: 'Nearly every day',
    questionProgress: 'Question {{current}} of {{total}}',
    percentComplete: '{{percent}}% Complete',
    previous: 'Previous',
    next: 'Next',
    complete: 'Complete',
    submitting: 'Submitting...',
    screeningCompleted: 'Screening Completed',
    screeningThanks: 'Thank you for completing the assessment.',
    totalScore: 'Total Score',
    severityLevel: 'Severity Level',
    recommendations: 'Recommendations:',
    returnToScreenings: 'Return to Screenings',
    takeScreening: 'Take Screening',
    questions: 'questions',
    recentScreenings: 'Recent Screenings',
    loadingHistory: 'Loading history...',
    beginWellbeingHistory: 'Begin your wellbeing history',
    firstScreeningMessage: 'Take your first screening to get started',
    score: 'Score',
    screeningSubmitError: 'Your screening could not be submitted. Please review your answers and try again.',
    notAvailable: 'Not available'
  },
  ta: {
    appTitle: 'CampusHealth பணியிடம்',
    adminDashboardTitle: 'நிர்வாக டாஷ்போர்டு',
    appSubtitle: 'AI ஆதரித்த கல்லூரி மனநலம்',
    dashboard: 'டாஷ்போர்டு',
    chatbot: 'AI உரையாடல்',
    screening: 'திரையாய்வு',
    screeningFull: 'மனநல திரையாய்வு',
    mlPredict: 'ML கணிப்பு',
    appointments: 'சந்திப்புகள்',
    counselors: 'ஆலோசகர்கள்',
    activities: 'செயல்பாடுகள்',
    activitiesManagement: 'செயல்பாடு மேலாண்மை',
    activityAnalysis: 'செயல்பாடு பகுப்பாய்வு',
    resources: 'வளங்கள்',
    forum: 'கருத்துக்களம்',
    profile: 'சுயவிவரம்',
    users: 'பயனர்கள்',
    analytics: 'பகுப்பாய்வு',
    reports: 'அறிக்கைகள்',
    adminStudio: 'நிர்வாக மையம்',
    adminPanel: 'நிர்வாகப் பலகம்',
    campusMentalHealth: 'கல்லூரி மனநலம்',
    wellnessSaaS: 'நலன் SaaS',
    settings: 'அமைப்புகள்',
    theme: 'தீம்',
    light: 'ஒளி',
    dark: 'இருள்',
    highContrast: 'அதிக எதிரொலி',
    fontSize: 'எழுத்து அளவு',
    small: 'சிறியது',
    medium: 'நடுத்தரம்',
    large: 'பெரியது',
    savingSettings: 'அமைப்புகள் சேமிக்கப்படுகின்றன…',
    notifications: 'அறிவிப்புகள்',
    unreadNotifications: 'அறிவிப்புகள், {{count}} படிக்கப்படாதவை',
    logout: 'வெளியேறு',
    language: 'மொழி',
    welcomeBack: 'மீண்டும் வரவேற்கிறோம், {{name}}!',
    department: 'துறை',
    semester: 'பருவம்',
    studentId: 'மாணவர் ஐடி',
    notAdded: 'சேர்க்கப்படவில்லை',
    retry: 'மீண்டும் முயற்சி',
    dashboardLoadError: 'சில டாஷ்போர்டு தரவை ஏற்ற முடியவில்லை. மீண்டும் முயற்சிக்கவும்.',
    loadingDashboard: 'உங்கள் டாஷ்போர்டு ஏற்றப்படுகிறது...',
    quickActions: 'விரைவு செயல்கள்',
    bookAppointment: 'சந்திப்பு பதிவு',
    bookAppointmentDescription: 'ஆலோசகருடன் அமர்வு திட்டமிடுங்கள்',
    startAIChat: 'AI உரையாடலை தொடங்கு',
    startAIChatDescription: 'உடனடி ஆதரவுக்கு AI உதவியாளருடன் பேசுங்கள்',
    takeAssessment: 'மதிப்பீடு எடு',
    takeAssessmentDescription: 'சரிபார்க்கப்பட்ட கருவிகளால் மனநலத்தை மதிப்பிடுங்கள்',
    wellnessEvents: 'நல நிகழ்வுகள்',
    wellnessEventsDescription: 'பட்டறைகள் மற்றும் கல்லூரி நல அமர்வுகளில் சேருங்கள்',
    viewCounselors: 'ஆலோசகர்களைக் காண்',
    viewCounselorsDescription: 'உங்களுக்கு பொருத்தமான ஆலோசகரைக் கண்டறியுங்கள்',
    mentalHealthSummary: 'மனநல சுருக்கம்',
    trackWellbeingBaseline: 'உங்கள் நல அடிப்படையை கண்காணிக்கவும்',
    trackWellbeingMessage: 'PHQ-9, GAD-7 மற்றும் அபாய சுருக்கத்தைப் பார்க்க திரையாய்வு எடுக்கவும்.',
    latestPhqScore: 'சமீபத்திய PHQ-9 மதிப்பெண்',
    latestGadScore: 'சமீபத்திய GAD-7 மதிப்பெண்',
    pendingPhq: 'PHQ-9 நிலுவையில்',
    pendingGad: 'GAD-7 நிலுவையில்',
    riskLevel: 'அபாய நிலை',
    lastAssessment: 'கடைசி மதிப்பீடு',
    aiChatSummary: 'AI உரையாடல் சுருக்கம்',
    continueChat: 'உரையாடலை தொடரவும்',
    startGuidedCheckin: 'வழிகாட்டும் AI சரிபார்ப்பை தொடங்குங்கள்',
    startGuidedCheckinMessage: 'வேண்டியபோது ரகசிய AI உரையாடலை தொடங்குங்கள்.',
    totalConversations: 'மொத்த உரையாடல்கள்',
    savedChatSessions: 'சேமிக்கப்பட்ட உரையாடல்கள்',
    lastChat: 'கடைசி உரையாடல்',
    recentSession: 'சமீபத்திய அமர்வு',
    upcomingWellnessEvents: 'வரவிருக்கும் நல நிகழ்வுகள்',
    browseEvents: 'நிகழ்வுகளை உலாவு',
    buildWellnessCalendar: 'உங்கள் நல காலண்டரை உருவாக்குங்கள்',
    buildWellnessCalendarMessage: 'கல்லூரி நல நிகழ்வில் பதிவு செய்தால் அது இங்கே தோன்றும்.',
    exploreEvents: 'நிகழ்வுகளை ஆராய்',
    recommendedEvents: 'பரிந்துரைக்கப்பட்ட நிகழ்வுகள்',
    viewAll: 'அனைத்தையும் காண்',
    noRecommendations: 'பரிந்துரைகள் இல்லை',
    noRecommendationsMessage: 'புதிய நல பரிந்துரைகள் நிகழ்வுகள் சேர்க்கப்படும் போது தோன்றும்.',
    appointmentSummary: 'சந்திப்பு சுருக்கம்',
    planCounselingSession: 'அடுத்த ஆலோசனை அமர்வை திட்டமிடுங்கள்',
    planCounselingSessionMessage: 'சந்திப்பு பதிவு செய்தால் தேதி, நேரம், வகை மற்றும் நிலை இங்கே தோன்றும்.',
    counselor: 'ஆலோசகர்',
    counselingSession: 'ஆலோசனை அமர்வு',
    date: 'தேதி',
    time: 'நேரம்',
    meetingType: 'சந்திப்பு வகை',
    online: 'ஆன்லைன்',
    inPerson: 'நேரில்',
    meetingId: 'சந்திப்பு ஐடி',
    openMeeting: 'சந்திப்பை திற',
    recentActivity: 'சமீபத்திய செயல்பாடு',
    noRecentActivity: 'சமீபத்திய செயல்பாடு இல்லை',
    noRecentActivityMessage: 'சந்திப்பு புதுப்பிப்புகள், மதிப்பீடுகள் மற்றும் AI உரையாடல்கள் இங்கே தோன்றும்.',
    todaysMentalHealthTip: 'இன்றைய மனநல குறிப்பு',
    practiceGratitude: 'நன்றியுணர்வை பயிற்சி செய்யுங்கள்',
    gratitudeTip: 'இன்று நீங்கள் நன்றியுடன் நினைக்கும் மூன்று விஷயங்களை எழுதுங்கள். இது மனநிலையை மேம்படுத்த உதவும்.',
    welcomeCounselor: 'வரவேற்கிறோம், {{name}}',
    counselorIntro: 'சந்திப்புகளை நிர்வகிக்கவும், மாணவர் திரையாய்வுகளைப் பார்க்கவும், செய்திகளுக்கு பதிலளிக்கவும்.',
    viewAppointments: 'சந்திப்புகளைக் காண்',
    viewAppointmentsDescription: 'வரவிருக்கும் அமர்வுகளை மதிப்பாய்வு செய்து நிர்வகிக்கவும்',
    shareResources: 'வளங்களைப் பகிர்',
    shareResourcesDescription: 'மாணவர்களுக்கு பயனுள்ள பொருட்களை பரிந்துரைக்கவும்',
    activityAnalysisDescription: 'செயல்பாடுகளை உருவாக்கி முடிவுகளைப் பார்க்கவும்',
    community: 'சமூகம்',
    communityDescription: 'சக ஆதரவு உரையாடல்களில் ஈடுபடுங்கள்',
    welcomeAdministrator: 'வரவேற்கிறோம், நிர்வாகி',
    adminIntro: 'அமைப்பு பகுப்பாய்வு, பயனர்கள் மற்றும் அமைப்புகளுக்கு விரைவு அணுகல்.',
    viewPlatformUsage: 'தள பயன்பாட்டைக் காண்',
    manageUsers: 'பயனர்களை நிர்வகி',
    manageUsersDescription: 'பாத்திரங்கள், நிலை மற்றும் அனுமதிகள்',
    curateContent: 'உள்ளடக்கத்தைத் தேர்ந்து ஒப்புதல் அளி',
    chatbotIntroDescription: 'உடனடி மனநல ஆதரவும் வழிகாட்டுதலும் பெறுங்கள்',
    chatbotIntroTitle: 'உரையாடலை தொடங்கு',
    chatbotIntroBody: 'எங்கள் AI உரையாடல் 24/7 மனநல ஆதரவை வழங்க தயாராக உள்ளது.',
    startChat: 'உரையாடலை தொடங்கு',
    chatbotAssistantLabel: 'AI உதவியாளர்',
    typeMessage: 'உங்கள் செய்தியை தட்டச்சு செய்யுங்கள்...',
    chatbotGreetingFallback: 'வணக்கம்! நான் உங்கள் AI மனநல உதவியாளர். இன்று எப்படி உணர்கிறீர்கள்?',
    chatbotErrorFallback: 'மன்னிக்கவும், இப்போது பதிலளிக்க முடியவில்லை. சிறிது நேரத்தில் மீண்டும் முயற்சிக்கவும்.',
    screeningDescription: 'சரிபார்க்கப்பட்ட கருவிகளால் உங்கள் மனநலத்தை மதிப்பிடுங்கள்',
    phqDescription: 'மனச்சோர்வு திரையாய்வுக்கான PHQ-9',
    gadDescription: 'கவலை திரையாய்வுக்கான GAD-7',
    pssDescription: 'மனஅழுத்த மதிப்பீட்டுக்கான PSS-10',
    phqQ1: 'செயல்களில் ஆர்வம் அல்லது மகிழ்ச்சி குறைதல்',
    phqQ2: 'மனச்சோர்வு, துயரம் அல்லது நம்பிக்கையின்மை உணர்வு',
    phqQ3: 'தூங்க சிரமம், தூக்கம் தொடராமல் போதல் அல்லது அதிகமாக தூங்குதல்',
    phqQ4: 'சோர்வு அல்லது சக்தி குறைவு',
    phqQ5: 'பசி குறைதல் அல்லது அதிகமாக உண்பது',
    phqQ6: 'உங்களைப் பற்றி மோசமாக உணருதல் அல்லது தோல்வியடைந்ததாக நினைத்தல்',
    phqQ7: 'படிப்பது அல்லது தொலைக்காட்சி பார்ப்பது போன்றவற்றில் கவனம் செலுத்த சிரமம்',
    phqQ8: 'மெதுவாக நகருதல்/பேசுதல் அல்லது மிகுந்த அமைதியின்மை',
    phqQ9: 'இல்லாமல் போனால் நல்லது அல்லது உங்களை காயப்படுத்த வேண்டும் என்ற எண்ணங்கள்',
    gadQ1: 'பதட்டம், கவலை அல்லது நெருடல் உணர்வு',
    gadQ2: 'கவலைப்படுவதை நிறுத்த அல்லது கட்டுப்படுத்த முடியாமை',
    gadQ3: 'பல விஷயங்களைப் பற்றி அதிகமாக கவலைப்படுதல்',
    gadQ4: 'சாந்தமாக இருக்க சிரமம்',
    gadQ5: 'அமைதியாக உட்கார முடியாத அளவுக்கு அமைதியின்மை',
    gadQ6: 'எளிதில் எரிச்சல் அல்லது கோபம் வருதல்',
    gadQ7: 'ஏதோ மோசமானது நடக்கலாம் என்ற பயம்',
    pssQ1: 'கடந்த மாதத்தில் எதிர்பாராத நிகழ்வால் எவ்வளவு அடிக்கடி வருத்தமடைந்தீர்கள்?',
    pssQ2: 'முக்கிய விஷயங்களை கட்டுப்படுத்த முடியவில்லை என்று எவ்வளவு அடிக்கடி உணர்ந்தீர்கள்?',
    pssQ3: 'நெருடல் மற்றும் மனஅழுத்தம் எவ்வளவு அடிக்கடி உணர்ந்தீர்கள்?',
    pssQ4: 'தனிப்பட்ட பிரச்சினைகளை கையாள முடியும் என்ற நம்பிக்கை எவ்வளவு அடிக்கடி இருந்தது?',
    pssQ5: 'விஷயங்கள் உங்கள் வழியில் நடக்கின்றன என்று எவ்வளவு அடிக்கடி உணர்ந்தீர்கள்?',
    pssQ6: 'செய்ய வேண்டியவற்றை சமாளிக்க முடியவில்லை என்று எவ்வளவு அடிக்கடி உணர்ந்தீர்கள்?',
    pssQ7: 'வாழ்க்கைச் சிரமங்களை கட்டுப்படுத்த முடிந்தது என்று எவ்வளவு அடிக்கடி உணர்ந்தீர்கள்?',
    pssQ8: 'விஷயங்கள் உங்கள் கட்டுப்பாட்டில் உள்ளன என்று எவ்வளவு அடிக்கடி உணர்ந்தீர்கள்?',
    pssQ9: 'உங்கள் கட்டுப்பாட்டுக்கு வெளியான விஷயங்களால் எவ்வளவு அடிக்கடி கோபமடைந்தீர்கள்?',
    pssQ10: 'சிரமங்கள் குவிந்து சமாளிக்க முடியாத அளவுக்கு உள்ளன என்று எவ்வளவு அடிக்கடி உணர்ந்தீர்கள்?',
    notAtAll: 'எதுவும் இல்லை',
    severalDays: 'சில நாட்கள்',
    moreThanHalfDays: 'நாட்களின் பாதிக்கும் மேல்',
    nearlyEveryDay: 'கிட்டத்தட்ட தினமும்',
    questionProgress: 'கேள்வி {{current}} / {{total}}',
    percentComplete: '{{percent}}% முடிந்தது',
    previous: 'முந்தையது',
    next: 'அடுத்து',
    complete: 'முடி',
    submitting: 'சமர்ப்பிக்கிறது...',
    screeningCompleted: 'திரையாய்வு முடிந்தது',
    screeningThanks: 'மதிப்பீட்டை முடித்ததற்கு நன்றி.',
    totalScore: 'மொத்த மதிப்பெண்',
    severityLevel: 'தீவிர நிலை',
    recommendations: 'பரிந்துரைகள்:',
    returnToScreenings: 'திரையாய்வுகளுக்கு திரும்பு',
    takeScreening: 'திரையாய்வு எடு',
    questions: 'கேள்விகள்',
    recentScreenings: 'சமீபத்திய திரையாய்வுகள்',
    loadingHistory: 'வரலாறு ஏற்றப்படுகிறது...',
    beginWellbeingHistory: 'உங்கள் நல வரலாற்றை தொடங்குங்கள்',
    firstScreeningMessage: 'தொடங்க உங்கள் முதல் திரையாய்வை எடுக்கவும்',
    score: 'மதிப்பெண்',
    screeningSubmitError: 'உங்கள் திரையாய்வை சமர்ப்பிக்க முடியவில்லை. பதில்களை சரிபார்த்து மீண்டும் முயற்சிக்கவும்.',
    notAvailable: 'கிடைக்கவில்லை'
  },
  te: {
    appTitle: 'CampusHealth వర్క్‌స్పేస్',
    adminDashboardTitle: 'అడ్మిన్ డాష్‌బోర్డ్',
    appSubtitle: 'AI ఆధారిత క్యాంపస్ మానసిక ఆరోగ్యం',
    dashboard: 'డాష్‌బోర్డ్',
    chatbot: 'AI చాట్‌బాట్',
    screening: 'స్క్రీనింగ్',
    screeningFull: 'మానసిక ఆరోగ్య స్క్రీనింగ్',
    mlPredict: 'ML అంచనా',
    appointments: 'అపాయింట్‌మెంట్లు',
    counselors: 'కౌన్సెలర్లు',
    activities: 'కార్యకలాపాలు',
    activitiesManagement: 'కార్యకలాపాల నిర్వహణ',
    activityAnalysis: 'కార్యకలాప విశ్లేషణ',
    resources: 'వనరులు',
    forum: 'ఫోరం',
    profile: 'ప్రొఫైల్',
    users: 'వినియోగదారులు',
    analytics: 'విశ్లేషణలు',
    reports: 'నివేదికలు',
    adminStudio: 'అడ్మిన్ స్టూడియో',
    adminPanel: 'అడ్మిన్ ప్యానెల్',
    campusMentalHealth: 'క్యాంపస్ మానసిక ఆరోగ్యం',
    wellnessSaaS: 'వెల్‌నెస్ SaaS',
    settings: 'సెట్టింగ్స్',
    theme: 'థీమ్',
    light: 'లైట్',
    dark: 'డార్క్',
    highContrast: 'హై కాంట్రాస్ట్',
    fontSize: 'ఫాంట్ పరిమాణం',
    small: 'చిన్నది',
    medium: 'మధ్యస్థం',
    large: 'పెద్దది',
    savingSettings: 'సెట్టింగ్స్ సేవ్ అవుతున్నాయి…',
    notifications: 'నోటిఫికేషన్లు',
    unreadNotifications: 'నోటిఫికేషన్లు, {{count}} చదవనివి',
    logout: 'లాగ్ అవుట్',
    language: 'భాష',
    welcomeBack: 'మళ్లీ స్వాగతం, {{name}}!',
    department: 'విభాగం',
    semester: 'సెమిస్టర్',
    studentId: 'స్టూడెంట్ ఐడి',
    notAdded: 'చేర్చలేదు',
    retry: 'మళ్లీ ప్రయత్నించండి',
    dashboardLoadError: 'కొంత డాష్‌బోర్డ్ డేటా లోడ్ కాలేదు. దయచేసి మళ్లీ ప్రయత్నించండి.',
    loadingDashboard: 'మీ డాష్‌బోర్డ్ లోడ్ అవుతోంది...',
    quickActions: 'త్వరిత చర్యలు',
    bookAppointment: 'అపాయింట్‌మెంట్ బుక్ చేయండి',
    bookAppointmentDescription: 'కౌన్సెలర్‌తో సెషన్ షెడ్యూల్ చేయండి',
    startAIChat: 'AI చాట్ ప్రారంభించండి',
    startAIChatDescription: 'తక్షణ సహాయం కోసం AI చాట్‌బాట్‌తో మాట్లాడండి',
    takeAssessment: 'అసెస్‌మెంట్ తీసుకోండి',
    takeAssessmentDescription: 'ధృవీకరించిన సాధనాలతో మీ మానసిక ఆరోగ్యాన్ని అంచనా వేయండి',
    wellnessEvents: 'వెల్‌నెస్ ఈవెంట్లు',
    wellnessEventsDescription: 'వర్క్‌షాపులు మరియు క్యాంపస్ వెల్‌బీయింగ్ సెషన్లలో పాల్గొనండి',
    viewCounselors: 'కౌన్సెలర్లను చూడండి',
    viewCounselorsDescription: 'మీకు సరైన కౌన్సెలర్‌ను కనుగొనండి',
    mentalHealthSummary: 'మానసిక ఆరోగ్య సారాంశం',
    trackWellbeingBaseline: 'మీ వెల్‌బీయింగ్ బేస్‌లైన్‌ను ట్రాక్ చేయండి',
    trackWellbeingMessage: 'మీ తాజా PHQ-9, GAD-7 మరియు రిస్క్ సారాంశం చూడటానికి స్క్రీనింగ్ తీసుకోండి.',
    latestPhqScore: 'తాజా PHQ-9 స్కోర్',
    latestGadScore: 'తాజా GAD-7 స్కోర్',
    pendingPhq: 'PHQ-9 పెండింగ్',
    pendingGad: 'GAD-7 పెండింగ్',
    riskLevel: 'రిస్క్ స్థాయి',
    lastAssessment: 'చివరి అసెస్‌మెంట్',
    aiChatSummary: 'AI చాట్ సారాంశం',
    continueChat: 'చాట్ కొనసాగించండి',
    startGuidedCheckin: 'గైడెడ్ AI చెక్-ఇన్ ప్రారంభించండి',
    startGuidedCheckinMessage: 'మీకు అవసరమైనప్పుడు గోప్యమైన AI చాట్ ప్రారంభించండి.',
    totalConversations: 'మొత్తం సంభాషణలు',
    savedChatSessions: 'సేవ్ చేసిన చాట్ సెషన్లు',
    lastChat: 'చివరి చాట్',
    recentSession: 'ఇటీవలి సెషన్',
    upcomingWellnessEvents: 'రాబోయే వెల్‌నెస్ ఈవెంట్లు',
    browseEvents: 'ఈవెంట్లు బ్రౌజ్ చేయండి',
    buildWellnessCalendar: 'మీ వెల్‌నెస్ క్యాలెండర్ నిర్మించండి',
    buildWellnessCalendarMessage: 'క్యాంపస్ వెల్‌నెస్ ఈవెంట్‌కు నమోదు చేస్తే అది ఇక్కడ కనిపిస్తుంది.',
    exploreEvents: 'ఈవెంట్లు అన్వేషించండి',
    recommendedEvents: 'సిఫార్సు చేసిన ఈవెంట్లు',
    viewAll: 'అన్నీ చూడండి',
    noRecommendations: 'సిఫార్సులు లేవు',
    noRecommendationsMessage: 'కొత్త వెల్‌బీయింగ్ సిఫార్సులు ఈవెంట్లు జోడించినప్పుడు కనిపిస్తాయి.',
    appointmentSummary: 'అపాయింట్‌మెంట్ సారాంశం',
    planCounselingSession: 'మీ తదుపరి కౌన్సెలింగ్ సెషన్‌ను ప్లాన్ చేయండి',
    planCounselingSessionMessage: 'అపాయింట్‌మెంట్ బుక్ చేస్తే తేదీ, సమయం, మీటింగ్ రకం మరియు స్థితి ఇక్కడ కనిపిస్తాయి.',
    counselor: 'కౌన్సెలర్',
    counselingSession: 'కౌన్సెలింగ్ సెషన్',
    date: 'తేదీ',
    time: 'సమయం',
    meetingType: 'మీటింగ్ రకం',
    online: 'ఆన్‌లైన్',
    inPerson: 'ప్రత్యక్షంగా',
    meetingId: 'మీటింగ్ ఐడి',
    openMeeting: 'మీటింగ్ తెరవండి',
    recentActivity: 'ఇటీవలి కార్యకలాపం',
    noRecentActivity: 'ఇటీవలి కార్యకలాపం లేదు',
    noRecentActivityMessage: 'అపాయింట్‌మెంట్ అప్‌డేట్లు, అసెస్‌మెంట్లు మరియు AI సంభాషణలు ఇక్కడ కనిపిస్తాయి.',
    todaysMentalHealthTip: 'ఈరోజు మానసిక ఆరోగ్య సూచన',
    practiceGratitude: 'కృతజ్ఞతను సాధన చేయండి',
    gratitudeTip: 'ఈరోజు మీరు కృతజ్ఞతతో ఉన్న మూడు విషయాలను రాయండి. ఈ సాధన మీ మూడ్‌ను మెరుగుపరచవచ్చు.',
    welcomeCounselor: 'స్వాగతం, {{name}}',
    counselorIntro: 'మీ అపాయింట్‌మెంట్లు నిర్వహించండి, విద్యార్థుల స్క్రీనింగ్‌లు చూడండి, సందేశాలకు స్పందించండి.',
    viewAppointments: 'అపాయింట్‌మెంట్లు చూడండి',
    viewAppointmentsDescription: 'రాబోయే సెషన్లను సమీక్షించి నిర్వహించండి',
    shareResources: 'వనరులు పంచుకోండి',
    shareResourcesDescription: 'విద్యార్థులకు ఉపయోగకరమైన పదార్థాలను సిఫార్సు చేయండి',
    activityAnalysisDescription: 'కార్యకలాపాలు సృష్టించి ఫలితాలను చూడండి',
    community: 'సమాజం',
    communityDescription: 'పియర్ సపోర్ట్ థ్రెడ్లలో పాల్గొనండి',
    welcomeAdministrator: 'స్వాగతం, అడ్మినిస్ట్రేటర్',
    adminIntro: 'సిస్టమ్ విశ్లేషణలు, వినియోగదారులు మరియు సెట్టింగ్స్‌కు త్వరిత ప్రాప్యత.',
    viewPlatformUsage: 'ప్లాట్‌ఫారమ్ వినియోగం చూడండి',
    manageUsers: 'వినియోగదారులను నిర్వహించండి',
    manageUsersDescription: 'పాత్రలు, స్థితి మరియు అనుమతులు',
    curateContent: 'కంటెంట్‌ను క్యురేట్ చేసి ఆమోదించండి',
    chatbotIntroDescription: 'తక్షణ మానసిక ఆరోగ్య సహాయం మరియు మార్గదర్శనం పొందండి',
    chatbotIntroTitle: 'సంభాషణ ప్రారంభించండి',
    chatbotIntroBody: 'మా AI చాట్‌బాట్ 24/7 మానసిక ఆరోగ్య సహాయం అందించడానికి సిద్ధంగా ఉంది.',
    startChat: 'చాట్ ప్రారంభించండి',
    chatbotAssistantLabel: 'AI సహాయకుడు',
    typeMessage: 'మీ సందేశాన్ని టైప్ చేయండి...',
    chatbotGreetingFallback: 'నమస్తే! నేను మీ AI మానసిక ఆరోగ్య సహాయకుడిని. ఈరోజు మీరు ఎలా ఉన్నారు?',
    chatbotErrorFallback: 'క్షమించండి, ప్రస్తుతం స్పందించలేకపోయాను. దయచేసి మళ్లీ ప్రయత్నించండి.',
    screeningDescription: 'ధృవీకరించిన సాధనాలతో మీ మానసిక ఆరోగ్యాన్ని అంచనా వేయండి',
    phqDescription: 'డిప్రెషన్ స్క్రీనింగ్ కోసం PHQ-9',
    gadDescription: 'ఆందోళన స్క్రీనింగ్ కోసం GAD-7',
    pssDescription: 'స్ట్రెస్ అసెస్‌మెంట్ కోసం PSS-10',
    phqQ1: 'పనులపై ఆసక్తి లేదా ఆనందం తగ్గడం',
    phqQ2: 'బాధగా, నిరుత్సాహంగా లేదా ఆశలేకుండా అనిపించడం',
    phqQ3: 'నిద్రపోవడంలో ఇబ్బంది, నిద్ర కొనసాగకపోవడం లేదా ఎక్కువగా నిద్రపోవడం',
    phqQ4: 'అలసటగా లేదా శక్తి తక్కువగా అనిపించడం',
    phqQ5: 'ఆకలి తగ్గడం లేదా ఎక్కువగా తినడం',
    phqQ6: 'మీ గురించి చెడుగా అనిపించడం లేదా విఫలమయ్యానని భావించడం',
    phqQ7: 'చదవడం లేదా టీవీ చూడడం వంటి వాటిపై దృష్టి పెట్టడంలో ఇబ్బంది',
    phqQ8: 'చాలా నెమ్మదిగా కదలడం/మాట్లాడడం లేదా చాలా ఆందోళనగా ఉండడం',
    phqQ9: 'లేకపోతే మంచిదనిపించడం లేదా మీకు హాని చేసుకోవాలనే ఆలోచనలు',
    gadQ1: 'నర్వస్‌గా, ఆందోళనగా లేదా టెన్షన్‌గా అనిపించడం',
    gadQ2: 'ఆందోళనను ఆపలేకపోవడం లేదా నియంత్రించలేకపోవడం',
    gadQ3: 'వివిధ విషయాల గురించి ఎక్కువగా ఆందోళన చెందడం',
    gadQ4: 'రిలాక్స్ అవ్వడంలో ఇబ్బంది',
    gadQ5: 'నిశ్చలంగా కూర్చోలేనంత అస్థిరంగా ఉండడం',
    gadQ6: 'సులభంగా చిరాకు లేదా కోపం రావడం',
    gadQ7: 'ఏదో చెడు జరగవచ్చనే భయం',
    pssQ1: 'గత నెలలో అనుకోని సంఘటన వల్ల ఎంత తరచుగా కలత చెందారు?',
    pssQ2: 'ముఖ్యమైన విషయాలను నియంత్రించలేకపోయానని ఎంత తరచుగా అనిపించింది?',
    pssQ3: 'నర్వస్‌గా మరియు ఒత్తిడిగా ఎంత తరచుగా అనిపించింది?',
    pssQ4: 'వ్యక్తిగత సమస్యలను నిర్వహించగలననే నమ్మకం ఎంత తరచుగా కలిగింది?',
    pssQ5: 'విషయాలు మీకు అనుకూలంగా జరుగుతున్నాయని ఎంత తరచుగా అనిపించింది?',
    pssQ6: 'చేయాల్సిన వాటిని ఎదుర్కోలేకపోయానని ఎంత తరచుగా అనిపించింది?',
    pssQ7: 'జీవితంలోని చికాకులను నియంత్రించగలిగానని ఎంత తరచుగా అనిపించింది?',
    pssQ8: 'విషయాలు మీ నియంత్రణలో ఉన్నాయని ఎంత తరచుగా అనిపించింది?',
    pssQ9: 'మీ నియంత్రణకు బయట ఉన్న విషయాల వల్ల ఎంత తరచుగా కోపం వచ్చింది?',
    pssQ10: 'సమస్యలు పేరుకుపోయి అధిగమించలేనంతగా ఉన్నాయని ఎంత తరచుగా అనిపించింది?',
    notAtAll: 'అసలు కాదు',
    severalDays: 'కొన్ని రోజులు',
    moreThanHalfDays: 'రోజులలో సగానికి మించి',
    nearlyEveryDay: 'దాదాపు ప్రతిరోజూ',
    questionProgress: 'ప్రశ్న {{current}} / {{total}}',
    percentComplete: '{{percent}}% పూర్తైంది',
    previous: 'మునుపటి',
    next: 'తర్వాత',
    complete: 'పూర్తి',
    submitting: 'సమర్పిస్తోంది...',
    screeningCompleted: 'స్క్రీనింగ్ పూర్తైంది',
    screeningThanks: 'అసెస్‌మెంట్ పూర్తి చేసినందుకు ధన్యవాదాలు.',
    totalScore: 'మొత్తం స్కోర్',
    severityLevel: 'తీవ్రత స్థాయి',
    recommendations: 'సిఫార్సులు:',
    returnToScreenings: 'స్క్రీనింగ్‌లకు తిరుగు',
    takeScreening: 'స్క్రీనింగ్ తీసుకోండి',
    questions: 'ప్రశ్నలు',
    recentScreenings: 'ఇటీవలి స్క్రీనింగ్‌లు',
    loadingHistory: 'చరిత్ర లోడ్ అవుతోంది...',
    beginWellbeingHistory: 'మీ వెల్‌బీయింగ్ చరిత్రను ప్రారంభించండి',
    firstScreeningMessage: 'ప్రారంభించడానికి మీ మొదటి స్క్రీనింగ్ తీసుకోండి',
    score: 'స్కోర్',
    screeningSubmitError: 'మీ స్క్రీనింగ్ సమర్పించలేకపోయాం. సమాధానాలను తనిఖీ చేసి మళ్లీ ప్రయత్నించండి.',
    notAvailable: 'అందుబాటులో లేదు'
  },
  kn: {
    appTitle: 'CampusHealth ಕಾರ್ಯಕ್ಷೇತ್ರ',
    adminDashboardTitle: 'ನಿರ್ವಹಣಾ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    appSubtitle: 'AI ಆಧಾರಿತ ಕ್ಯಾಂಪಸ್ ಮಾನಸಿಕ ಆರೋಗ್ಯ',
    dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    chatbot: 'AI ಚಾಟ್‌ಬಾಟ್',
    screening: 'ಸ್ಕ್ರೀನಿಂಗ್',
    screeningFull: 'ಮಾನಸಿಕ ಆರೋಗ್ಯ ಸ್ಕ್ರೀನಿಂಗ್',
    mlPredict: 'ML ಊಹೆ',
    appointments: 'ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್‌ಗಳು',
    counselors: 'ಕೌನ್ಸೆಲರ್‌ಗಳು',
    activities: 'ಚಟುವಟಿಕೆಗಳು',
    activitiesManagement: 'ಚಟುವಟಿಕೆ ನಿರ್ವಹಣೆ',
    activityAnalysis: 'ಚಟುವಟಿಕೆ ವಿಶ್ಲೇಷಣೆ',
    resources: 'ಸಂಪನ್ಮೂಲಗಳು',
    forum: 'ಫೋರಮ್',
    profile: 'ಪ್ರೊಫೈಲ್',
    users: 'ಬಳಕೆದಾರರು',
    analytics: 'ವಿಶ್ಲೇಷಣೆ',
    reports: 'ವರದಿಗಳು',
    adminStudio: 'ನಿರ್ವಹಣಾ ಸ್ಟುಡಿಯೋ',
    adminPanel: 'ನಿರ್ವಹಣಾ ಫಲಕ',
    campusMentalHealth: 'ಕ್ಯಾಂಪಸ್ ಮಾನಸಿಕ ಆರೋಗ್ಯ',
    wellnessSaaS: 'ವೆಲ್‌ನೆಸ್ SaaS',
    settings: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    theme: 'ಥೀಮ್',
    light: 'ಲೈಟ್',
    dark: 'ಡಾರ್ಕ್',
    highContrast: 'ಹೈ ಕಾಂಟ್ರಾಸ್ಟ್',
    fontSize: 'ಅಕ್ಷರ ಗಾತ್ರ',
    small: 'ಚಿಕ್ಕದು',
    medium: 'ಮಧ್ಯಮ',
    large: 'ದೊಡ್ಡದು',
    savingSettings: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು ಉಳಿಯುತ್ತಿವೆ…',
    notifications: 'ಅಧಿಸೂಚನೆಗಳು',
    unreadNotifications: 'ಅಧಿಸೂಚನೆಗಳು, {{count}} ಓದದವು',
    logout: 'ಲಾಗ್ ಔಟ್',
    language: 'ಭಾಷೆ',
    welcomeBack: 'ಮತ್ತೆ ಸ್ವಾಗತ, {{name}}!',
    department: 'ವಿಭಾಗ',
    semester: 'ಸೆಮಿಸ್ಟರ್',
    studentId: 'ವಿದ್ಯಾರ್ಥಿ ಐಡಿ',
    notAdded: 'ಸೇರಿಸಿಲ್ಲ',
    retry: 'ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ',
    dashboardLoadError: 'ಕೆಲವು ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ಡೇಟಾ ಲೋಡ್ ಆಗಲಿಲ್ಲ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    loadingDashboard: 'ನಿಮ್ಮ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
    quickActions: 'ತ್ವರಿತ ಕ್ರಮಗಳು',
    bookAppointment: 'ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್ ಬುಕ್ ಮಾಡಿ',
    bookAppointmentDescription: 'ಕೌನ್ಸೆಲರ್ ಜೊತೆ ಸೆಷನ್ ನಿಗದಿಪಡಿಸಿ',
    startAIChat: 'AI ಚಾಟ್ ಪ್ರಾರಂಭಿಸಿ',
    startAIChatDescription: 'ತಕ್ಷಣದ ಬೆಂಬಲಕ್ಕಾಗಿ AI ಚಾಟ್‌ಬಾಟ್ ಜೊತೆ ಮಾತನಾಡಿ',
    takeAssessment: 'ಮೌಲ್ಯಮಾಪನ ತೆಗೆದುಕೊಳ್ಳಿ',
    takeAssessmentDescription: 'ಮಾನ್ಯಗೊಂಡ ಸಾಧನಗಳಿಂದ ನಿಮ್ಮ ಮಾನಸಿಕ ಆರೋಗ್ಯವನ್ನು ಅಳೆಯಿರಿ',
    wellnessEvents: 'ವೆಲ್‌ನೆಸ್ ಕಾರ್ಯಕ್ರಮಗಳು',
    wellnessEventsDescription: 'ವರ್ಕ್‌ಶಾಪ್‌ಗಳು ಮತ್ತು ಕ್ಯಾಂಪಸ್ ಕಲ್ಯಾಣ ಸೆಷನ್‌ಗಳಲ್ಲಿ ಸೇರಿ',
    viewCounselors: 'ಕೌನ್ಸೆಲರ್‌ಗಳನ್ನು ನೋಡಿ',
    viewCounselorsDescription: 'ನಿಮಗೆ ಸರಿಯಾದ ಕೌನ್ಸೆಲರ್ ಕಂಡುಹಿಡಿಯಿರಿ',
    mentalHealthSummary: 'ಮಾನಸಿಕ ಆರೋಗ್ಯ ಸಾರಾಂಶ',
    trackWellbeingBaseline: 'ನಿಮ್ಮ ಕಲ್ಯಾಣ ಆಧಾರವನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
    trackWellbeingMessage: 'ನಿಮ್ಮ ಇತ್ತೀಚಿನ PHQ-9, GAD-7 ಮತ್ತು ಅಪಾಯ ಸಾರಾಂಶ ನೋಡಲು ಸ್ಕ್ರೀನಿಂಗ್ ತೆಗೆದುಕೊಳ್ಳಿ.',
    latestPhqScore: 'ಇತ್ತೀಚಿನ PHQ-9 ಸ್ಕೋರ್',
    latestGadScore: 'ಇತ್ತೀಚಿನ GAD-7 ಸ್ಕೋರ್',
    pendingPhq: 'PHQ-9 ಬಾಕಿ',
    pendingGad: 'GAD-7 ಬಾಕಿ',
    riskLevel: 'ಅಪಾಯ ಮಟ್ಟ',
    lastAssessment: 'ಕೊನೆಯ ಮೌಲ್ಯಮಾಪನ',
    aiChatSummary: 'AI ಚಾಟ್ ಸಾರಾಂಶ',
    continueChat: 'ಚಾಟ್ ಮುಂದುವರಿಸಿ',
    startGuidedCheckin: 'ಮಾರ್ಗದರ್ಶಿತ AI ಚೆಕ್-ಇನ್ ಪ್ರಾರಂಭಿಸಿ',
    startGuidedCheckinMessage: 'ಬೇಕಾದಾಗ ಗೌಪ್ಯ AI ಚಾಟ್ ಪ್ರಾರಂಭಿಸಿ.',
    totalConversations: 'ಒಟ್ಟು ಸಂಭಾಷಣೆಗಳು',
    savedChatSessions: 'ಉಳಿಸಿದ ಚಾಟ್ ಸೆಷನ್‌ಗಳು',
    lastChat: 'ಕೊನೆಯ ಚಾಟ್',
    recentSession: 'ಇತ್ತೀಚಿನ ಸೆಷನ್',
    upcomingWellnessEvents: 'ಮುಂಬರುವ ವೆಲ್‌ನೆಸ್ ಕಾರ್ಯಕ್ರಮಗಳು',
    browseEvents: 'ಕಾರ್ಯಕ್ರಮಗಳನ್ನು ಬ್ರೌಸ್ ಮಾಡಿ',
    buildWellnessCalendar: 'ನಿಮ್ಮ ವೆಲ್‌ನೆಸ್ ಕ್ಯಾಲೆಂಡರ್ ನಿರ್ಮಿಸಿ',
    buildWellnessCalendarMessage: 'ಕ್ಯಾಂಪಸ್ ವೆಲ್‌ನೆಸ್ ಕಾರ್ಯಕ್ರಮಕ್ಕೆ ನೋಂದಾಯಿಸಿದರೆ ಅದು ಇಲ್ಲಿ ಕಾಣಿಸುತ್ತದೆ.',
    exploreEvents: 'ಕಾರ್ಯಕ್ರಮಗಳನ್ನು ಅನ್ವೇಷಿಸಿ',
    recommendedEvents: 'ಶಿಫಾರಸು ಮಾಡಿದ ಕಾರ್ಯಕ್ರಮಗಳು',
    viewAll: 'ಎಲ್ಲವನ್ನೂ ನೋಡಿ',
    noRecommendations: 'ಶಿಫಾರಸುಗಳಿಲ್ಲ',
    noRecommendationsMessage: 'ಹೊಸ ಕಲ್ಯಾಣ ಶಿಫಾರಸುಗಳು ಕಾರ್ಯಕ್ರಮಗಳು ಸೇರಿಸಿದಾಗ ಕಾಣಿಸುತ್ತವೆ.',
    appointmentSummary: 'ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್ ಸಾರಾಂಶ',
    planCounselingSession: 'ಮುಂದಿನ ಕೌನ್ಸೆಲಿಂಗ್ ಸೆಷನ್ ಯೋಜಿಸಿ',
    planCounselingSessionMessage: 'ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್ ಬುಕ್ ಮಾಡಿದರೆ ದಿನಾಂಕ, ಸಮಯ, ಮೀಟಿಂಗ್ ಪ್ರಕಾರ ಮತ್ತು ಸ್ಥಿತಿ ಇಲ್ಲಿ ಕಾಣಿಸುತ್ತವೆ.',
    counselor: 'ಕೌನ್ಸೆಲರ್',
    counselingSession: 'ಕೌನ್ಸೆಲಿಂಗ್ ಸೆಷನ್',
    date: 'ದಿನಾಂಕ',
    time: 'ಸಮಯ',
    meetingType: 'ಮೀಟಿಂಗ್ ಪ್ರಕಾರ',
    online: 'ಆನ್‌ಲೈನ್',
    inPerson: 'ನೇರವಾಗಿ',
    meetingId: 'ಮೀಟಿಂಗ್ ಐಡಿ',
    openMeeting: 'ಮೀಟಿಂಗ್ ತೆರೆಯಿರಿ',
    recentActivity: 'ಇತ್ತೀಚಿನ ಚಟುವಟಿಕೆ',
    noRecentActivity: 'ಇತ್ತೀಚಿನ ಚಟುವಟಿಕೆ ಇಲ್ಲ',
    noRecentActivityMessage: 'ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್ ನವೀಕರಣಗಳು, ಮೌಲ್ಯಮಾಪನಗಳು ಮತ್ತು AI ಸಂಭಾಷಣೆಗಳು ಇಲ್ಲಿ ಕಾಣಿಸುತ್ತವೆ.',
    todaysMentalHealthTip: 'ಇಂದಿನ ಮಾನಸಿಕ ಆರೋಗ್ಯ ಸಲಹೆ',
    practiceGratitude: 'ಕೃತಜ್ಞತೆಯನ್ನು ಅಭ್ಯಾಸ ಮಾಡಿ',
    gratitudeTip: 'ಇಂದು ನೀವು ಕೃತಜ್ಞರಾಗಿರುವ ಮೂರು ವಿಷಯಗಳನ್ನು ಬರೆಯಿರಿ. ಇದು ಮನೋಭಾವವನ್ನು ಸುಧಾರಿಸಬಹುದು.',
    welcomeCounselor: 'ಸ್ವಾಗತ, {{name}}',
    counselorIntro: 'ನಿಮ್ಮ ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್‌ಗಳನ್ನು ನಿರ್ವಹಿಸಿ, ವಿದ್ಯಾರ್ಥಿ ಸ್ಕ್ರೀನಿಂಗ್‌ಗಳನ್ನು ನೋಡಿ, ಸಂದೇಶಗಳಿಗೆ ಪ್ರತಿಕ್ರಿಯಿಸಿ.',
    viewAppointments: 'ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್‌ಗಳನ್ನು ನೋಡಿ',
    viewAppointmentsDescription: 'ಮುಂಬರುವ ಸೆಷನ್‌ಗಳನ್ನು ಪರಿಶೀಲಿಸಿ ಮತ್ತು ನಿರ್ವಹಿಸಿ',
    shareResources: 'ಸಂಪನ್ಮೂಲಗಳನ್ನು ಹಂಚಿ',
    shareResourcesDescription: 'ವಿದ್ಯಾರ್ಥಿಗಳಿಗೆ ಉಪಯುಕ್ತ ವಸ್ತುಗಳನ್ನು ಶಿಫಾರಸು ಮಾಡಿ',
    activityAnalysisDescription: 'ಚಟುವಟಿಕೆಗಳನ್ನು ರಚಿಸಿ ಮತ್ತು ಫಲಿತಾಂಶಗಳನ್ನು ನೋಡಿ',
    community: 'ಸಮುದಾಯ',
    communityDescription: 'ಪಿಯರ್ ಬೆಂಬಲ ಚರ್ಚೆಗಳಲ್ಲಿ ಭಾಗವಹಿಸಿ',
    welcomeAdministrator: 'ಸ್ವಾಗತ, ನಿರ್ವಾಹಕ',
    adminIntro: 'ಸಿಸ್ಟಮ್ ವಿಶ್ಲೇಷಣೆ, ಬಳಕೆದಾರರು ಮತ್ತು ಸೆಟ್ಟಿಂಗ್‌ಗಳಿಗೆ ತ್ವರಿತ ಪ್ರವೇಶ.',
    viewPlatformUsage: 'ಪ್ಲಾಟ್‌ಫಾರ್ಮ್ ಬಳಕೆ ನೋಡಿ',
    manageUsers: 'ಬಳಕೆದಾರರನ್ನು ನಿರ್ವಹಿಸಿ',
    manageUsersDescription: 'ಪಾತ್ರಗಳು, ಸ್ಥಿತಿ ಮತ್ತು ಅನುಮತಿಗಳು',
    curateContent: 'ವಿಷಯವನ್ನು ಆಯ್ಕೆ ಮಾಡಿ ಅನುಮೋದಿಸಿ',
    chatbotIntroDescription: 'ತಕ್ಷಣದ ಮಾನಸಿಕ ಆರೋಗ್ಯ ಬೆಂಬಲ ಮತ್ತು ಮಾರ್ಗದರ್ಶನ ಪಡೆಯಿರಿ',
    chatbotIntroTitle: 'ಸಂಭಾಷಣೆ ಪ್ರಾರಂಭಿಸಿ',
    chatbotIntroBody: 'ನಮ್ಮ AI ಚಾಟ್‌ಬಾಟ್ 24/7 ಮಾನಸಿಕ ಆರೋಗ್ಯ ಬೆಂಬಲ ನೀಡಲು ಸಿದ್ಧವಾಗಿದೆ.',
    startChat: 'ಚಾಟ್ ಪ್ರಾರಂಭಿಸಿ',
    chatbotAssistantLabel: 'AI ಸಹಾಯಕ',
    typeMessage: 'ನಿಮ್ಮ ಸಂದೇಶವನ್ನು ಟೈಪ್ ಮಾಡಿ...',
    chatbotGreetingFallback: 'ನಮಸ್ಕಾರ! ನಾನು ನಿಮ್ಮ AI ಮಾನಸಿಕ ಆರೋಗ್ಯ ಸಹಾಯಕ. ಇಂದು ನಿಮಗೆ ಹೇಗಿದೆ?',
    chatbotErrorFallback: 'ಕ್ಷಮಿಸಿ, ಈಗ ಪ್ರತಿಕ್ರಿಯಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    screeningDescription: 'ಮಾನ್ಯಗೊಂಡ ಸಾಧನಗಳಿಂದ ನಿಮ್ಮ ಮಾನಸಿಕ ಆರೋಗ್ಯವನ್ನು ಅಳೆಯಿರಿ',
    phqDescription: 'ಅವಸಾದ ಸ್ಕ್ರೀನಿಂಗ್‌ಗಾಗಿ PHQ-9',
    gadDescription: 'ಆತಂಕ ಸ್ಕ್ರೀನಿಂಗ್‌ಗಾಗಿ GAD-7',
    pssDescription: 'ಒತ್ತಡ ಮೌಲ್ಯಮಾಪನಕ್ಕಾಗಿ PSS-10',
    phqQ1: 'ಕೆಲಸಗಳಲ್ಲಿ ಆಸಕ್ತಿ ಅಥವಾ ಸಂತೋಷ ಕಡಿಮೆಯಾಗುವುದು',
    phqQ2: 'ದುಃಖ, ನಿರಾಶೆ ಅಥವಾ ಆಶಾಹೀನತೆ ಅನುಭವಿಸುವುದು',
    phqQ3: 'ನಿದ್ರೆಗೆ ತೊಂದರೆ, ನಿದ್ರೆ ಮುಂದುವರಿಯದಿರುವುದು ಅಥವಾ ಹೆಚ್ಚು ನಿದ್ರೆ',
    phqQ4: 'ದಣಿವು ಅಥವಾ ಶಕ್ತಿ ಕಡಿಮೆ ಅನಿಸುವುದು',
    phqQ5: 'ಆಹಾರಾಸಕ್ತಿ ಕಡಿಮೆ ಅಥವಾ ಹೆಚ್ಚು ತಿನ್ನುವುದು',
    phqQ6: 'ನಿಮ್ಮ ಬಗ್ಗೆ ಕೆಟ್ಟದಾಗಿ ಭಾವಿಸುವುದು ಅಥವಾ ವಿಫಲವಾದೆ ಎಂದು ಅನಿಸುವುದು',
    phqQ7: 'ಓದುವುದು ಅಥವಾ ಟಿವಿ ನೋಡುವುದರಲ್ಲಿ ಗಮನ ಕೇಂದ್ರೀಕರಿಸಲು ತೊಂದರೆ',
    phqQ8: 'ತುಂಬಾ ನಿಧಾನವಾಗಿ ಚಲಿಸುವುದು/ಮಾತನಾಡುವುದು ಅಥವಾ ತುಂಬಾ ಅಶಾಂತವಾಗಿರುವುದು',
    phqQ9: 'ಇಲ್ಲದಿದ್ದರೆ ಒಳ್ಳೆಯದು ಅಥವಾ ನಿಮಗೆ ಹಾನಿ ಮಾಡಿಕೊಳ್ಳಬೇಕು ಎಂಬ ಆಲೋಚನೆಗಳು',
    gadQ1: 'ನರ್ವಸ್, ಆತಂಕ ಅಥವಾ ಒತ್ತಡದ ಅನುಭವ',
    gadQ2: 'ಚಿಂತೆಯನ್ನು ನಿಲ್ಲಿಸಲು ಅಥವಾ ನಿಯಂತ್ರಿಸಲು ಸಾಧ್ಯವಾಗದಿರುವುದು',
    gadQ3: 'ವಿವಿಧ ವಿಷಯಗಳ ಬಗ್ಗೆ ಹೆಚ್ಚು ಚಿಂತಿಸುವುದು',
    gadQ4: 'ಆರಾಮವಾಗಿರಲು ತೊಂದರೆ',
    gadQ5: 'ಸ್ಥಿರವಾಗಿ ಕುಳಿತುಕೊಳ್ಳಲು ಕಷ್ಟವಾಗುವಷ್ಟು ಅಶಾಂತಿ',
    gadQ6: 'ಸುಲಭವಾಗಿ ಕಿರಿಕಿರಿ ಅಥವಾ ಕೋಪ ಬರುವುದು',
    gadQ7: 'ಏನೋ ಕೆಟ್ಟದ್ದು ಸಂಭವಿಸಬಹುದು ಎಂಬ ಭಯ',
    pssQ1: 'ಕಳೆದ ತಿಂಗಳಲ್ಲಿ ಅನಿರೀಕ್ಷಿತ ಘಟನೆಯಿಂದ ಎಷ್ಟು ಬಾರಿ ಬೇಸರಗೊಂಡಿದ್ದೀರಿ?',
    pssQ2: 'ಮುಖ್ಯ ವಿಷಯಗಳನ್ನು ನಿಯಂತ್ರಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ ಎಂದು ಎಷ್ಟು ಬಾರಿ ಅನಿಸಿತು?',
    pssQ3: 'ನರ್ವಸ್ ಮತ್ತು ಒತ್ತಡದ ಅನುಭವ ಎಷ್ಟು ಬಾರಿ ಆಯಿತು?',
    pssQ4: 'ವೈಯಕ್ತಿಕ ಸಮಸ್ಯೆಗಳನ್ನು ನಿಭಾಯಿಸಬಲ್ಲೆ ಎಂಬ ವಿಶ್ವಾಸ ಎಷ್ಟು ಬಾರಿ ಇತ್ತು?',
    pssQ5: 'ವಿಷಯಗಳು ನಿಮ್ಮ ರೀತಿಯಲ್ಲಿ ಸಾಗುತ್ತಿವೆ ಎಂದು ಎಷ್ಟು ಬಾರಿ ಅನಿಸಿತು?',
    pssQ6: 'ಮಾಡಬೇಕಾದ ಎಲ್ಲವನ್ನು ನಿಭಾಯಿಸಲು ಆಗಲಿಲ್ಲ ಎಂದು ಎಷ್ಟು ಬಾರಿ ಅನಿಸಿತು?',
    pssQ7: 'ಜೀವನದ ಕಿರಿಕಿರಿಗಳನ್ನು ನಿಯಂತ್ರಿಸಲು ಸಾಧ್ಯವಾಯಿತು ಎಂದು ಎಷ್ಟು ಬಾರಿ ಅನಿಸಿತು?',
    pssQ8: 'ವಿಷಯಗಳು ನಿಮ್ಮ ನಿಯಂತ್ರಣದಲ್ಲಿ ಇವೆ ಎಂದು ಎಷ್ಟು ಬಾರಿ ಅನಿಸಿತು?',
    pssQ9: 'ನಿಮ್ಮ ನಿಯಂತ್ರಣದ ಹೊರಗಿನ ವಿಷಯಗಳಿಂದ ಎಷ್ಟು ಬಾರಿ ಕೋಪಗೊಂಡಿದ್ದೀರಿ?',
    pssQ10: 'ಸಮಸ್ಯೆಗಳು ತುಂಬಾ ಹೆಚ್ಚಾಗಿ ಮೀರಿ ಹೋಗಿವೆ ಎಂದು ಎಷ್ಟು ಬಾರಿ ಅನಿಸಿತು?',
    notAtAll: 'ಏನೂ ಇಲ್ಲ',
    severalDays: 'ಕೆಲವು ದಿನಗಳು',
    moreThanHalfDays: 'ದಿನಗಳ ಅರ್ಧಕ್ಕಿಂತ ಹೆಚ್ಚು',
    nearlyEveryDay: 'ಸುಮಾರು ಪ್ರತಿದಿನ',
    questionProgress: 'ಪ್ರಶ್ನೆ {{current}} / {{total}}',
    percentComplete: '{{percent}}% ಪೂರ್ಣ',
    previous: 'ಹಿಂದಿನದು',
    next: 'ಮುಂದೆ',
    complete: 'ಪೂರ್ಣಗೊಳಿಸಿ',
    submitting: 'ಸಲ್ಲಿಸಲಾಗುತ್ತಿದೆ...',
    screeningCompleted: 'ಸ್ಕ್ರೀನಿಂಗ್ ಪೂರ್ಣಗೊಂಡಿದೆ',
    screeningThanks: 'ಮೌಲ್ಯಮಾಪನ ಪೂರ್ಣಗೊಳಿಸಿದಕ್ಕಾಗಿ ಧನ್ಯವಾದಗಳು.',
    totalScore: 'ಒಟ್ಟು ಸ್ಕೋರ್',
    severityLevel: 'ತೀವ್ರತೆ ಮಟ್ಟ',
    recommendations: 'ಶಿಫಾರಸುಗಳು:',
    returnToScreenings: 'ಸ್ಕ್ರೀನಿಂಗ್‌ಗಳಿಗೆ ಮರಳಿ',
    takeScreening: 'ಸ್ಕ್ರೀನಿಂಗ್ ತೆಗೆದುಕೊಳ್ಳಿ',
    questions: 'ಪ್ರಶ್ನೆಗಳು',
    recentScreenings: 'ಇತ್ತೀಚಿನ ಸ್ಕ್ರೀನಿಂಗ್‌ಗಳು',
    loadingHistory: 'ಇತಿಹಾಸ ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
    beginWellbeingHistory: 'ನಿಮ್ಮ ಕಲ್ಯಾಣ ಇತಿಹಾಸ ಪ್ರಾರಂಭಿಸಿ',
    firstScreeningMessage: 'ಪ್ರಾರಂಭಿಸಲು ನಿಮ್ಮ ಮೊದಲ ಸ್ಕ್ರೀನಿಂಗ್ ತೆಗೆದುಕೊಳ್ಳಿ',
    score: 'ಸ್ಕೋರ್',
    screeningSubmitError: 'ನಿಮ್ಮ ಸ್ಕ್ರೀನಿಂಗ್ ಸಲ್ಲಿಸಲಾಗಲಿಲ್ಲ. ಉತ್ತರಗಳನ್ನು ಪರಿಶೀಲಿಸಿ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    notAvailable: 'ಲಭ್ಯವಿಲ್ಲ'
  }
};

const template = (value, params = {}) => (
  Object.entries(params).reduce(
    (text, [key, replacement]) => text.replaceAll(`{{${key}}}`, String(replacement)),
    value
  )
);

const clearGoogleTranslateCookies = () => {
  if (typeof document === 'undefined') return;
  const expired = 'googtrans=; expires=Thu, 01 Jan 1970 00:00:00 UTC; path=/;';
  document.cookie = expired;
  if (window.location.hostname) {
    document.cookie = `googtrans=; expires=Thu, 01 Jan 1970 00:00:00 UTC; domain=.${window.location.hostname}; path=/;`;
  }
};

const applyDocumentLanguage = (languageCode) => {
  if (typeof document === 'undefined') return false;
  const languageInfo = languages[languageCode] || languages.en;
  const languageFontClasses = Object.values(languages).map((language) => language.font);

  document.documentElement.lang = languageInfo.code;
  document.documentElement.classList.remove(...languageFontClasses);
  document.documentElement.classList.add(languageInfo.font);
  document.documentElement.dir = 'ltr';
  document.documentElement.setAttribute('translate', 'no');
  document.documentElement.classList.add('notranslate');
  document.body?.setAttribute('translate', 'no');
  document.body?.classList.add('notranslate');

  return false;
};

export function LanguageProvider({ children }) {
  const [currentLanguage, setCurrentLanguage] = useState(() => {
    const savedLanguage = localStorage.getItem('language') || 'en';
    return languages[savedLanguage] ? savedLanguage : 'en';
  });
  const [isRTL, setIsRTL] = useState(false);

  useEffect(() => {
    setIsRTL(applyDocumentLanguage(currentLanguage));
    localStorage.setItem('language', currentLanguage);
    clearGoogleTranslateCookies();
  }, [currentLanguage]);

  const changeLanguage = (languageCode) => {
    if (!languages[languageCode]) return;
    setCurrentLanguage(languageCode);
  };

  const t = (key, params) => {
    const value = translations[currentLanguage]?.[key] || translations.en[key] || key;
    return template(value, params);
  };

  const getCurrentLanguageInfo = () => languages[currentLanguage] || languages.en;

  const value = {
    currentLanguage,
    languages,
    isRTL,
    changeLanguage,
    t,
    getCurrentLanguageInfo
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
